/* Packs the crew art into js/crew-assets.js as data URIs, so the game works
   offline and as a single file. Run after changing anything in assets/crew/. */
'use strict';
const fs = require('fs');
const path = require('path');
const dir = path.join(__dirname, '..', 'assets', 'crew');
const files = { banner: 'crew.jpg' };
['bull', 'bear', 'fox', 'wolf'].forEach((k) => { files[k] = k + '.jpg'; files[k + 'Cut'] = k + '-cut.webp'; });
const out = {};
for (const [key, f] of Object.entries(files)) {
  const ext = path.extname(f).slice(1).replace('jpg', 'jpeg');
  out[key] = `data:image/${ext};base64,` + fs.readFileSync(path.join(dir, f)).toString('base64');
}
fs.writeFileSync(path.join(__dirname, '..', 'js', 'crew-assets.js'),
  '/* Generated by scripts/build-assets.js. Do not edit by hand. */\nwindow.CQ_CREW_ART = ' + JSON.stringify(out) + ';\n');
console.log('crew-assets.js', Math.round(JSON.stringify(out).length / 1024) + ' KB');
